-- Real Poconos STR providers
-- Run in Supabase SQL Editor after supabase/schema.sql

insert into public.providers (
  id, slug, name, category, counties, service_areas, tier, phone, email, website,
  rating, review_count, verified, tagline, description, services, response_time,
  insured, licensed, year_founded, price_note, pricing_notes, featured_resorts,
  is_demo, is_active
) values
(
  uuid_generate_v4(),
  'mountain-cleaning',
  'Mountain Cleaning Services LLC',
  'cleaning',
  ARRAY['Monroe','Carbon','Pike']::text[],
  ARRAY['Blakeslee','Lake Harmony','Albrightsville','Tobyhanna','Mount Pocono','Tannersville']::text[],
  'featured',
  '(570) 781-5070',
  NULL,
  'mountaincleaningservicesllc.com',
  4.9,
  38,
  true,
  'STR turnovers + hot tub balancing + guest-ready guarantee.',
  'Mountain Cleaning Services handles complete turnover cleaning for short-term rentals across the Poconos. Services include deep cleaning, linen handling, hot tub maintenance and balancing, guest-ready staging, and 24/7 emergency support for check-in day issues.',
  ARRAY['STR turnovers','Hot tub service','Linen handling','Guest-ready guarantee','Emergency support']::text[],
  'Under 2 hours',
  true,
  false,
  2012,
  NULL,
  'STR turnovers + hot tub balancing + guest-ready guarantee.',
  ARRAY['Lake Harmony','Camelback / Tannersville']::text[],
  true,
  true
),
(
  uuid_generate_v4(),
  'hot-tub-hygiene',
  'Hot Tub Hygiene',
  'hottub',
  ARRAY['Monroe','Carbon']::text[],
  ARRAY['East Stroudsburg','Stroudsburg','Lake Harmony','Tobyhanna']::text[],
  'premium',
  'Request via site',
  'Contact@Hottubhygiene.com',
  'hottubhygiene.com',
  4.8,
  22,
  true,
  'Hot tub chemical balancing, drain & refill, and maintenance for vacation rentals.',
  'Hot Tub Hygiene specializes exclusively in hot tub care for Pocono vacation rentals. Chemical balancing, cleaning, cover replacement, drain and refill, and winterization services. Online booking, text support, and guest-safety certified technicians.',
  ARRAY['Chemical balancing','Drain & refill','Cover cleaning/replacement','Winterization','24/7 guest support']::text[],
  'Same day',
  true,
  true,
  2018,
  NULL,
  '$80-$150 per visit; chemical balancing, drain/refill.',
  ARRAY['Lake Harmony']::text[],
  true,
  true
),
(
  uuid_generate_v4(),
  'blue-titan',
  'Blue Titan Plumbing & Heating',
  'hvac',
  ARRAY['Monroe','Carbon','Pike','Wayne']::text[],
  ARRAY['Monroe','Carbon','Pike','Wayne']::text[],
  'premium',
  '(570) 545-6199',
  NULL,
  'bluetitanhvac.com',
  4.7,
  45,
  true,
  'HVAC, plumbing, and seasonal winterization for vacation homes.',
  'Blue Titan provides full-service plumbing, heating, and air conditioning for Pocono vacation rentals. Seasonal winterization packages, 24/7 emergency service, smart thermostat integration, and direct billing to property managers.',
  ARRAY['HVAC repair/install','Plumbing','Winterization','Smart thermostat setup','24/7 emergency']::text[],
  '24/7 emergency',
  true,
  true,
  2010,
  NULL,
  'Seasonal winterization packages, 24/7 vacation-home focus.',
  ARRAY['Camelback / Tannersville','Blue Mountain','Shawnee']::text[],
  true,
  true
),
(
  uuid_generate_v4(),
  'the-tidy-bear',
  'The Tidy Bear',
  'trash',
  ARRAY['Monroe','Carbon']::text[],
  ARRAY['Poconos-wide']::text[],
  'standard',
  'Request via site',
  NULL,
  'thetidybear.com',
  4.6,
  19,
  true,
  'Weekly trash valet, recycling pickup, and can cleaning for STR hosts.',
  'The Tidy Bear handles trash and recycling removal for vacation rental hosts. Weekly pickup and return of cans, recycling sorting, and seasonal deep-cleaning of outdoor receptacles. Flat monthly rate so hosts never worry about garbage day.',
  ARRAY['Weekly trash valet','Recycling pickup','Can cleaning','Seasonal deep clean','Text reminders']::text[],
  'Weekly scheduled',
  true,
  false,
  2021,
  NULL,
  'From $49/month for weekly can take-out & return.',
  ARRAY['Poconos-wide']::text[],
  true,
  true
);
