-- Demo seed data (32 sample providers marked is_demo = true)
-- Run after schema.sql. Replace with real providers via /api/import or the claim form.

insert into public.providers (
  id, slug, name, category, counties, service_areas, tier, phone, email, website,
  rating, review_count, verified, tagline, description, services, response_time,
  insured, licensed, year_founded, price_note, is_demo, is_active
) values
(
  uuid_generate_v4(),
  'pocono-peak-clean',
  'Pocono Peak Clean',
  'cleaning',
  ARRAY["Monroe","Carbon"]::text[],
  ARRAY["Stroudsburg","East Stroudsburg","Tannersville","Scotrun"]::text[],
  'featured',
  '5705550101',
  'hello@poconopeakclean.com',
  'poconopeakclean.com',
  4.9,
  41,
  true,
  'Turnover-ready cleaning trusted by 30+ Poconos hosts',
  'Family-run turnover cleaning crew serving Monroe and Carbon counties since 2019. We specialize in same-day turnovers, full inventory restocking, and photo-ready staging. Every clean includes a 30-point checklist and a photo report sent straight to your phone.',
  ARRAY["Same-day turnover","Deep cleans","Restocking","Photo reports","Mold & mildew treatment"]::text[],
  'Under 2 hours',
  true,
  false,
  2019,
  'From $140 / turnover',
  true,
  true
),
(
  uuid_generate_v4(),
  'fresh-stay-cleaning',
  'Fresh Stay Cleaning Co.',
  'cleaning',
  ARRAY["Monroe"]::text[],
  ARRAY["East Stroudsburg","Swiftwater","Bartonsville"]::text[],
  'standard',
  '5705550102',
  'book@freshstaycleaning.com',
  NULL,
  4.8,
  27,
  true,
  'Reliable turnovers with a same-day guarantee',
  'A dedicated crew focused on STR turnovers in the Stroudsburg area. Same-day service for same-day bookings, laundry pickup available, and consistent staffing so guests never see a different crew twice in a row.',
  ARRAY["Turnovers","Laundry pickup","Supply restock","Guest-ready staging"]::text[],
  'Same day',
  true,
  false,
  2021,
  'From $125 / turnover',
  true,
  true
),
(
  uuid_generate_v4(),
  'summit-housekeeping',
  'Summit Housekeeping',
  'cleaning',
  ARRAY["Monroe","Wayne"]::text[],
  ARRAY["Mount Pocono","Tobyhanna","Gouldsboro"]::text[],
  'standard',
  '5705550103',
  'summit@summithousekeeping.com',
  NULL,
  4.7,
  19,
  true,
  'Weekend-peak turnovers without the stress',
  'We built our schedule around the Poconos weekend rush: Friday and Sunday crews that handle check-in and check-out waves, plus mid-week deep cleans for back-to-back bookings.',
  ARRAY["Turnovers","Mid-week deep cleans","Hot tub care","Trash & recycling"]::text[],
  'Under 4 hours',
  true,
  false,
  2020,
  'From $130 / turnover',
  true,
  true
),
(
  uuid_generate_v4(),
  'alpine-turnover-crew',
  'Alpine Turnover Crew',
  'cleaning',
  ARRAY["Carbon","Monroe"]::text[],
  ARRAY["Lake Harmony","Albrightsville","Blakeslee","Pocono Lake"]::text[],
  'premium',
  '5705550104',
  'crew@alpineturnover.com',
  'alpineturnover.com',
  4.9,
  33,
  true,
  'Lake-area specialists with 2-hour response',
  'Cleaning crews based in the Lake Harmony corridor covering the busiest lake-rental market in the Poconos. Two-hour emergency response, snow-ready access plans, and detailed turnover checklists that cut guest complaints in half.',
  ARRAY["Turnovers","Emergency cleans","Hot tub servicing","Seasonal deep cleans"]::text[],
  '2 hours',
  true,
  false,
  2018,
  'From $150 / turnover',
  true,
  true
),
(
  uuid_generate_v4(),
  'keystone-clean-team',
  'Keystone Clean Team',
  'cleaning',
  ARRAY["Wayne"]::text[],
  ARRAY["Honesdale","Hawley","Lake Wallenpaupack"]::text[],
  'standard',
  '5705550105',
  'info@keystonecleanteam.com',
  NULL,
  4.6,
  14,
  false,
  'Wayne County''s STR turnover specialists',
  'Serving the Lake Wallenpaupack rental market with turnovers, restocking, and a 24-hour booking window. Trusted by local property managers for dependable weekend coverage.',
  ARRAY["Turnovers","Restocking","Pre-arrival checks"]::text[],
  'Within 1 business day',
  true,
  false,
  2021,
  'From $125 / turnover',
  true,
  true
),
(
  uuid_generate_v4(),
  'white-pine-cleaning',
  'White Pine Cleaning',
  'cleaning',
  ARRAY["Pike"]::text[],
  ARRAY["Bushkill","Dingmans Ferry","Milford"]::text[],
  'free',
  '5705550106',
  'whitepinecleaning@gmail.com',
  NULL,
  4.5,
  9,
  false,
  'New crew building STR turnover clients',
  'Established residential cleaning company expanding into vacation rental turnovers in Pike County. Flexible scheduling and competitive introductory pricing for first-time STR clients.',
  ARRAY["Turnovers","Residential cleans","Move-out cleans"]::text[],
  'Within 1 business day',
  true,
  false,
  2023,
  'From $110 / turnover',
  true,
  true
),
(
  uuid_generate_v4(),
  'mountain-man-repairs',
  'Mountain Man Repairs',
  'maintenance',
  ARRAY["Monroe","Carbon"]::text[],
  ARRAY["Tannersville","Stroudsburg","Cresco","Albrightsville"]::text[],
  'featured',
  '5705550111',
  'jim@mountainmanrepairs.com',
  'mountainmanrepairs.com',
  4.8,
  52,
  true,
  'The handyman hosts call first — 15+ years',
  'Full-service handyman for STR owners: drywall, painting, deck repair, furniture assembly, smart locks, and preventative winterization. We keep a punch-list app so owners know exactly what was fixed and when.',
  ARRAY["Drywall & paint","Deck & fence repair","Furniture assembly","Smart lock installs","Winterization"]::text[],
  'Within 4 hours',
  true,
  true,
  2009,
  '$85 / hr',
  true,
  true
),
(
  uuid_generate_v4(),
  'pocono-handyman-pro',
  'Pocono Handyman Pro',
  'maintenance',
  ARRAY["Monroe"]::text[],
  ARRAY["Stroudsburg","East Stroudsburg","Saylorsburg"]::text[],
  'standard',
  '5705550112',
  'mike@poconohandymanpro.com',
  NULL,
  4.7,
  31,
  true,
  'Small repairs done right, same week',
  'Solo handyman with a strong local reputation for fast, fair-priced repairs on vacation rentals. Most small jobs are quoted same-day and completed within the week.',
  ARRAY["General repairs","Caulking & sealing","Door & lock repairs","Light carpentry"]::text[],
  'Same day',
  true,
  false,
  2016,
  '$75 / hr',
  true,
  true
),
(
  uuid_generate_v4(),
  'lake-effect-maintenance',
  'Lake Effect Maintenance',
  'maintenance',
  ARRAY["Wayne","Pike"]::text[],
  ARRAY["Hawley","Honesdale","Lake Wallenpaupack","Milford"]::text[],
  'standard',
  '5705550113',
  'service@lakeeffectmaint.com',
  NULL,
  4.6,
  18,
  false,
  'Two-county coverage for lakefront rentals',
  'Handyman and light maintenance services built around lakefront rentals: dock repairs, bulkhead checks, water-damage touch-ups, and seasonal opening/closing help.',
  ARRAY["Dock & bulkhead repair","Water damage touch-up","Seasonal opening/closing","General repairs"]::text[],
  'Within 24 hours',
  true,
  false,
  2019,
  '$80 / hr',
  true,
  true
),
(
  uuid_generate_v4(),
  'ridge-and-valley-repair',
  'Ridge & Valley Repair',
  'maintenance',
  ARRAY["Carbon"]::text[],
  ARRAY["Jim Thorpe","Lehighton","White Haven"]::text[],
  'standard',
  '5705550114',
  'ridgevalleyrepair@gmail.com',
  NULL,
  4.5,
  11,
  false,
  'Jim Thorpe area''s go-to fix-it pro',
  'Reliable handyman serving the Jim Thorpe and Lehighton corridor with repairs, painting, and light carpentry for boutique rentals and historic homes.',
  ARRAY["Repairs","Painting","Light carpentry","Gutter cleaning"]::text[],
  'Within 1 business day',
  true,
  false,
  2020,
  '$70 / hr',
  true,
  true
),
(
  uuid_generate_v4(),
  'timberline-property-care',
  'Timberline Property Care',
  'maintenance',
  ARRAY["Monroe"]::text[],
  ARRAY["Canadensis","Cresco","Swiftwater"]::text[],
  'free',
  '5705550115',
  'timberlinepc@gmail.com',
  NULL,
  4.4,
  6,
  false,
  'Growing crew taking on rental maintenance',
  'Property care crew expanding into STR maintenance. Seasonal packages available that combine lawn, snow, and handyman work into one predictable monthly bill.',
  ARRAY["General repairs","Seasonal maintenance packages","Exterior upkeep"]::text[],
  'Within 2 business days',
  false,
  false,
  2022,
  '$65 / hr',
  true,
  true
),
(
  uuid_generate_v4(),
  'pocono-climate-control',
  'Pocono Climate Control',
  'hvac',
  ARRAY["Monroe","Carbon"]::text[],
  ARRAY["East Stroudsburg","Tannersville","Lake Harmony"]::text[],
  'featured',
  '5705550121',
  'service@poconoclimate.com',
  'poconoclimate.com',
  4.8,
  44,
  true,
  'Licensed HVAC with STR-speed emergency service',
  'Licensed and insured HVAC contractor that keeps rental properties guest-ready year-round. 24/7 emergency heat and AC service, annual maintenance plans for STR owners, and direct billing to property managers.',
  ARRAY["Furnace repair","Heat pump service","AC tune-ups","Duct cleaning","24/7 emergency calls"]::text[],
  '24/7 emergency line',
  true,
  true,
  2011,
  '$120 diagnostic',
  true,
  true
),
(
  uuid_generate_v4(),
  'alpine-air-hvac',
  'Alpine Air HVAC',
  'hvac',
  ARRAY["Monroe"]::text[],
  ARRAY["Mount Pocono","Tobyhanna","Gouldsboro"]::text[],
  'standard',
  '5705550122',
  'office@alpineairhvac.com',
  NULL,
  4.6,
  22,
  true,
  'Heat pumps and mini-splits, done right',
  'Specialists in the heat pumps and mini-split systems common in newer Poconos rentals. Fast diagnostics, honest pricing, and after-hours availability for guest-facing breakdowns.',
  ARRAY["Mini-split install","Heat pump repair","Thermostat setup","Emergency service"]::text[],
  'Within 4 hours',
  true,
  true,
  2015,
  '$95 diagnostic',
  true,
  true
),
(
  uuid_generate_v4(),
  'high-country-hvac',
  'High Country Heating & Cooling',
  'hvac',
  ARRAY["Pike","Wayne"]::text[],
  ARRAY["Milford","Dingmans Ferry","Hawley"]::text[],
  'standard',
  '5705550123',
  'highcountryhvac@gmail.com',
  NULL,
  4.7,
  16,
  false,
  'Pike & Wayne county heating coverage',
  'Family-owned HVAC serving the northern Poconos with furnace tune-ups, propane system checks, and rental-property maintenance agreements.',
  ARRAY["Furnace tune-ups","Propane system checks","AC repair","Maintenance agreements"]::text[],
  'Within 1 business day',
  true,
  true,
  2017,
  '$110 diagnostic',
  true,
  true
),
(
  uuid_generate_v4(),
  'clearwater-plumbing',
  'Clearwater Plumbing',
  'plumbing',
  ARRAY["Monroe"]::text[],
  ARRAY["Stroudsburg","East Stroudsburg","Bartonsville"]::text[],
  'standard',
  '5705550131',
  'clearwaterplumbing@gmail.com',
  NULL,
  4.7,
  29,
  true,
  'Licensed plumbers for rental-ready fixes',
  'Licensed plumbing company experienced with STR-specific issues: clogged drains from guest use, water heater replacements, and frozen-pipe emergencies in mountain homes.',
  ARRAY["Drain cleaning","Water heaters","Frozen pipe repair","Leak detection"]::text[],
  'Within 4 hours',
  true,
  true,
  2013,
  '$150 service call',
  true,
  true
),
(
  uuid_generate_v4(),
  'pocono-pipeworks',
  'Pocono Pipeworks',
  'plumbing',
  ARRAY["Monroe","Carbon"]::text[],
  ARRAY["Tobyhanna","Pocono Lake","Albrightsville"]::text[],
  'standard',
  '5705550132',
  'poconopipeworks@gmail.com',
  NULL,
  4.5,
  13,
  false,
  'Rough-country plumbing for mountain homes',
  'Plumbers who understand well systems, septic-friendly fixes, and the quirks of mountain rentals. Preventive winterization plans available for remote properties.',
  ARRAY["Well systems","Septic-friendly repair","Winterization","Fixture replacement"]::text[],
  'Within 1 business day',
  true,
  true,
  2018,
  '$140 service call',
  true,
  true
),
(
  uuid_generate_v4(),
  'summit-plumbing-drain',
  'Summit Plumbing & Drain',
  'plumbing',
  ARRAY["Carbon"]::text[],
  ARRAY["Jim Thorpe","Lehighton","White Haven"]::text[],
  'free',
  '5705550133',
  'summitplumb@gmail.com',
  NULL,
  4.4,
  8,
  false,
  'Jim Thorpe plumbing, done local',
  'Local plumbing and drain service building a rental-property clientele in Carbon County. Fair rates and quick response on common guest-caused issues.',
  ARRAY["Drain clearing","Toilet repair","Fixture installs","Leak repair"]::text[],
  'Within 1 business day',
  true,
  true,
  2021,
  '$125 service call',
  true,
  true
),
(
  uuid_generate_v4(),
  'mountain-current-electric',
  'Mountain Current Electric',
  'electrical',
  ARRAY["Monroe"]::text[],
  ARRAY["Stroudsburg","Tannersville","Swiftwater"]::text[],
  'premium',
  '5705550141',
  'work@mountaincurrent.com',
  'mountaincurrent.com',
  4.9,
  37,
  true,
  'Licensed electricians for hot tubs & EV chargers',
  'Full-service electrical contractor popular with STR owners installing hot tubs, saunas, EV chargers, and smart-home systems. Code-compliant work with photos and permits handled for you.',
  ARRAY["Hot tub hookups","EV chargers","Panel upgrades","Smart-home wiring","Outdoor lighting"]::text[],
  'Within 4 hours',
  true,
  true,
  2012,
  '$135 service call',
  true,
  true
),
(
  uuid_generate_v4(),
  'keystone-voltage',
  'Keystone Voltage',
  'electrical',
  ARRAY["Wayne"]::text[],
  ARRAY["Honesdale","Hawley","Lake Wallenpaupack"]::text[],
  'standard',
  '5705550142',
  'keystonevoltage@gmail.com',
  NULL,
  4.6,
  15,
  false,
  'Wayne County electrical, rental-savvy',
  'Licensed electricians serving lake-area rentals with inspections, repair, and upgrade work. Familiar with the permit requirements that catch new STR owners by surprise.',
  ARRAY["Electrical repair","Inspections","Hot tub wiring","Fixture installs"]::text[],
  'Within 1 business day',
  true,
  true,
  2016,
  '$130 service call',
  true,
  true
),
(
  uuid_generate_v4(),
  'blue-ridge-electric',
  'Blue Ridge Electric Co.',
  'electrical',
  ARRAY["Pike"]::text[],
  ARRAY["Milford","Dingmans Ferry","Bushkill"]::text[],
  'standard',
  '5705550143',
  'blueridgeelectric@outlook.com',
  NULL,
  4.5,
  12,
  false,
  'Pike County electrical you can book in advance',
  'Small licensed electrical shop with online booking — rare in the region. Great for scheduled upgrades and seasonal lighting installs between bookings.',
  ARRAY["Panel work","Lighting installs","Repairs","Generator hookups"]::text[],
  'Within 1 business day',
  true,
  true,
  2019,
  '$125 service call',
  true,
  true
),
(
  uuid_generate_v4(),
  'pocono-greenscapes',
  'Pocono Greenscapes',
  'landscaping',
  ARRAY["Monroe"]::text[],
  ARRAY["Tannersville","Bartonsville","Stroudsburg"]::text[],
  'standard',
  '5705550151',
  'poconogreenscapes@gmail.com',
  NULL,
  4.7,
  21,
  true,
  'Curb appeal that shows up in your photos',
  'Landscaping designed to keep vacation rentals photo-ready: mowing, mulching, stone work, and seasonal color. Monthly plans that sync with your booking calendar.',
  ARRAY["Mowing","Mulching & beds","Stone & hardscape","Seasonal color"]::text[],
  'Within 1 business day',
  true,
  false,
  2017,
  'From $220 / month',
  true,
  true
),
(
  uuid_generate_v4(),
  'evergreen-lawn-landscape',
  'Evergreen Lawn & Landscape',
  'landscaping',
  ARRAY["Monroe"]::text[],
  ARRAY["Cresco","Canadensis","Effort"]::text[],
  'standard',
  '5705550152',
  'evergreenll@yahoo.com',
  NULL,
  4.5,
  10,
  false,
  'Keep the yard as clean as the interior',
  'Full lawn and landscape service for the quieter corners of Monroe County. Reliable weekly schedules and clean-up after every storm.',
  ARRAY["Lawn care","Brush clearing","Storm cleanup","Spring/fall cleanups"]::text[],
  'Within 2 business days',
  true,
  false,
  2020,
  'From $180 / month',
  true,
  true
),
(
  uuid_generate_v4(),
  'woodland-outdoor-services',
  'Woodland Outdoor Services',
  'landscaping',
  ARRAY["Carbon"]::text[],
  ARRAY["Lake Harmony","Albrightsville","Blakeslee"]::text[],
  'free',
  '5705550153',
  'woodlandoutdoors@gmail.com',
  NULL,
  4.4,
  7,
  false,
  'Outdoor maintenance for lake rentals',
  'Outdoor services for lake-area rentals: lawn care, brush control, fire-pit maintenance, and lakeside cleanup between seasons.',
  ARRAY["Lawn care","Fire-pit upkeep","Brush control","Lakeside cleanup"]::text[],
  'Within 2 business days',
  false,
  false,
  2021,
  'From $160 / month',
  true,
  true
),
(
  uuid_generate_v4(),
  'keystone-snow-pros',
  'Keystone Snow Pros',
  'snow-removal',
  ARRAY["Monroe","Carbon"]::text[],
  ARRAY["Stroudsburg","Tannersville","Lake Harmony","Blakeslee"]::text[],
  'featured',
  '5705550161',
  'dispatch@keystonesnowpros.com',
  'keystonesnowpros.com',
  4.8,
  26,
  true,
  'STR-first plowing with access guarantee',
  'Snow service built for rental hosts: guaranteed driveway and walkway access before check-in, 24/7 storm dispatch, and photo proof of service after every plow. Seasonal contracts hold your spot for winter bookings.',
  ARRAY["Driveway plowing","Walkway shoveling","Ice treatment","24/7 storm dispatch","Seasonal contracts"]::text[],
  '24/7 during storms',
  true,
  false,
  2018,
  'From $120 / storm',
  true,
  true
),
(
  uuid_generate_v4(),
  'north-slope-snow-ice',
  'North Slope Snow & Ice',
  'snow-removal',
  ARRAY["Carbon"]::text[],
  ARRAY["White Haven","Jim Thorpe","Albrightsville"]::text[],
  'standard',
  '5705550162',
  'northslopesnow@gmail.com',
  NULL,
  4.6,
  14,
  false,
  'Steep-driveway specialists for mountain homes',
  'We handle the steep, tricky driveways that other plows won''t touch. Snow, ice, and de-icing packages for rentals that host winter guests.',
  ARRAY["Steep-driveway plowing","De-icing","Roof raking","Seasonal contracts"]::text[],
  '24/7 during storms',
  true,
  false,
  2019,
  'From $140 / storm',
  true,
  true
),
(
  uuid_generate_v4(),
  'arctic-poconos-plow',
  'Arctic Poconos Plow',
  'snow-removal',
  ARRAY["Wayne","Pike"]::text[],
  ARRAY["Hawley","Honesdale","Milford"]::text[],
  'free',
  '5705550163',
  'arcticpoconosplow@gmail.com',
  NULL,
  4.5,
  9,
  false,
  'Northern Poconos plow service, per-storm or seasonal',
  'Flexible plowing service for the northern counties. Book per-storm or commit to a seasonal contract and never worry about check-in-day snow again.',
  ARRAY["Plowing","Shoveling","Ice treatment"]::text[],
  'Within 12 hours of storm end',
  true,
  false,
  2020,
  'From $100 / storm',
  true,
  true
),
(
  uuid_generate_v4(),
  'pocono-linen-supply',
  'Pocono Linen Supply',
  'linens',
  ARRAY["Monroe","Carbon"]::text[],
  ARRAY["East Stroudsburg","Tannersville","Lake Harmony"]::text[],
  'premium',
  '5705550171',
  'sales@poconolinens.com',
  'poconolinens.com',
  4.9,
  30,
  true,
  'Hotel-grade linens delivered on your turnover day',
  'Commercial-grade sheet sets, towel bundles, and amenities delivered and picked up on your exact turnover schedule. Barcode-tracked bundles so nothing goes missing between houses.',
  ARRAY["Sheet sets","Towel bundles","Amenity refills","Scheduled pickup","Barcode tracking"]::text[],
  'Same day',
  false,
  false,
  2019,
  'From $2.25 / bed set',
  true,
  true
),
(
  uuid_generate_v4(),
  'alpine-threads',
  'Alpine Threads Linen Co.',
  'linens',
  ARRAY["Monroe"]::text[],
  ARRAY["Mount Pocono","Tobyhanna","Gouldsboro"]::text[],
  'standard',
  '5705550172',
  'alpthreads@gmail.com',
  NULL,
  4.7,
  17,
  false,
  'Soft, consistent linens that earn 5-star reviews',
  'Linen rental for STR owners who want that hotel feel without the laundry headache. Consistent product so every guest gets the same great sheets.',
  ARRAY["Linen rental","Towel service","Bulk laundering"]::text[],
  'Within 1 business day',
  false,
  false,
  2020,
  'From $2.00 / bed set',
  true,
  true
),
(
  uuid_generate_v4(),
  'lakeside-laundry-co',
  'Lakeside Laundry Co.',
  'linens',
  ARRAY["Carbon","Wayne"]::text[],
  ARRAY["Lake Harmony","Albrightsville","Hawley","Lake Wallenpaupack"]::text[],
  'standard',
  '5705550173',
  'lakesidelaundry@gmail.com',
  NULL,
  4.6,
  13,
  false,
  'Lake-area linen service with same-week delivery',
  'Lake-district linen service covering the two biggest lake markets. Wash-and-fold for your own linens or full rental packages for new hosts.',
  ARRAY["Wash & fold","Linen packages","Towel bundles"]::text[],
  'Within 2 business days',
  false,
  false,
  2021,
  'From $1.80 / bed set',
  true,
  true
),
(
  uuid_generate_v4(),
  'pocono-property-photography',
  'Pocono Property Photography',
  'photography',
  ARRAY["Monroe","Carbon"]::text[],
  ARRAY["Stroudsburg","Tannersville","Lake Harmony"]::text[],
  'standard',
  '5705550181',
  'book@poconophoto.com',
  'poconopropertyphoto.com',
  4.8,
  24,
  true,
  'Photos that lift your ranking and nightly rate',
  'Real-estate and STR photographers who shoot twilight exteriors, HDR interiors, and 3D virtual tours. Hosts see higher click-through and bookings within weeks of a reshoot.',
  ARRAY["HDR interiors","Twilight exteriors","3D virtual tours","Drone video","Floor plans"]::text[],
  'Books within 1 week',
  false,
  false,
  2016,
  'From $275 / shoot',
  true,
  true
),
(
  uuid_generate_v4(),
  'lake-light-media',
  'Lake Light Media',
  'photography',
  ARRAY["Wayne","Pike"]::text[],
  ARRAY["Lake Wallenpaupack","Hawley","Milford"]::text[],
  'standard',
  '5705550182',
  'hello@lakelightmedia.com',
  NULL,
  4.7,
  15,
  false,
  'Lakefront property specialists',
  'Photography and video focused on lakefront and lake-view rentals. Drone footage of shoreline, docks, and sunset views that sell the lifestyle.',
  ARRAY["Interior photography","Drone footage","Property video","Twilight shoots"]::text[],
  'Books within 2 weeks',
  false,
  false,
  2019,
  'From $300 / shoot',
  true,
  true
),
(
  uuid_generate_v4(),
  'summit-staging-studio',
  'Summit Staging Studio',
  'photography',
  ARRAY["Monroe"]::text[],
  ARRAY["Tannersville","Mount Pocono","Cresco"]::text[],
  'free',
  '5705550183',
  'summitstaging@gmail.com',
  NULL,
  4.5,
  7,
  false,
  'Styling + photography for boutique rentals',
  'Small staging and photography studio helping boutique rentals and cabins stand out. Styling consultations, prop styling, and flat-lay product shots for amenities.',
  ARRAY["Interior styling","Prop styling","Product photography"]::text[],
  'Books within 2 weeks',
  false,
  false,
  2022,
  'From $200 / session',
  true,
  true
)
on conflict (slug) do nothing;
