import type { CategoryMeta, Provider } from "./types";

export const CATEGORIES: CategoryMeta[] = [
  {
    slug: "cleaning",
    label: "Turnover Cleaning",
    shortLabel: "Cleaning",
    description:
      "Turnover-ready crews that flip rentals between guests — sanitizing, restocking, and reporting.",
    icon: "🧽",
    typicalCost: "$125–$175 / turnover",
  },
  {
    slug: "maintenance",
    label: "Maintenance & Handyman",
    shortLabel: "Handyman",
    description:
      "General repairs, drywall, painting, furniture assembly, and seasonal maintenance.",
    icon: "🔧",
    typicalCost: "$75–$150 / hr",
  },
  {
    slug: "hvac",
    label: "HVAC",
    shortLabel: "HVAC",
    description:
      "Licensed heating & cooling techs for furnace, heat pump, AC, and duct servicing.",
    icon: "❄️",
    typicalCost: "$150–$450 / call",
  },
  {
    slug: "plumbing",
    label: "Plumbing",
    shortLabel: "Plumbing",
    description:
      "Licensed plumbers for leaks, water heaters, frozen pipes, and full repipes.",
    icon: "🚿",
    typicalCost: "$150–$400 / job",
  },
  {
    slug: "electrical",
    label: "Electrical",
    shortLabel: "Electrical",
    description:
      "Licensed electricians for wiring, EV chargers, hot tub hookups, and panel work.",
    icon: "⚡",
    typicalCost: "$150–$500 / job",
  },
  {
    slug: "landscaping",
    label: "Landscaping",
    shortLabel: "Landscaping",
    description:
      "Lawn care, brush clearing, mulch, and curb appeal that keeps listings photo-ready.",
    icon: "🌲",
    typicalCost: "$200–$600 / month",
  },
  {
    slug: "snow-removal",
    label: "Snow Removal",
    shortLabel: "Snow",
    description:
      "Plowing, shoveling, and ice treatment so guests and contractors can always get in.",
    icon: "❄️",
    typicalCost: "$100–$300 / storm",
  },
  {
    slug: "linens",
    label: "Linen Supply",
    shortLabel: "Linens",
    description:
      "Delivery and laundering of sheets, towels, and amenities on your turnover schedule.",
    icon: "🛏️",
    typicalCost: "$1.50–$4.00 / bed set",
  },
  {
    slug: "photography",
    label: "Photography & Staging",
    shortLabel: "Photography",
    description:
      "Pro photography, virtual tours, and staging that boosts click-through and nightly rates.",
    icon: "📷",
    typicalCost: "$200–$500 / shoot",
  },
  {
    slug: "suppliers",
    label: "Furniture & Supplies",
    shortLabel: "Suppliers",
    description:
      "Furniture, decor, smart-home devices, toiletries, and bulk amenities for STR owners.",
    icon: "🛋️",
    typicalCost: "Varies",
  },
  {
    slug: "hottub",
    label: "Hot Tub Service",
    shortLabel: "Hot Tubs",
    description: "Chemical balancing, drain and refill, cover care, and winterization for vacation rental hot tubs.",
    icon: "🛁",
    typicalCost: "$80–$150 / visit"
  },
  {
    slug: "pest",
    label: "Pest Control",
    shortLabel: "Pest",
    description: "Seasonal pest control and preventative treatments to keep vacation rentals guest-ready and complaint-free.",
    icon: "🐜",
    typicalCost: "$150–$300 / treatment"
  },
  {
    slug: "trash",
    label: "Trash Valet",
    shortLabel: "Trash",
    description: "Weekly trash and recycling pickup and return, can cleaning, and outdoor maintenance so hosts never worry about garbage day.",
    icon: "🗑️",
    typicalCost: "From $49 / month"
  },
];

export const PROVIDERS: Provider[] = [
  {
    slug: "pocono-peak-clean",
    name: "Pocono Peak Clean",
    category: "cleaning",
    counties: ["Monroe", "Carbon"],
    serviceAreas: ["Stroudsburg", "East Stroudsburg", "Tannersville", "Scotrun"],
    tier: "featured",
    phone: "5705550101",
    email: "hello@poconopeakclean.com",
    website: "poconopeakclean.com",
    rating: 4.9,
    reviewCount: 41,
    verified: true,
    tagline: "Turnover-ready cleaning trusted by 30+ Poconos hosts",
    description:
      "Family-run turnover cleaning crew serving Monroe and Carbon counties since 2019. We specialize in same-day turnovers, full inventory restocking, and photo-ready staging. Every clean includes a 30-point checklist and a photo report sent straight to your phone.",
    services: ["Same-day turnover", "Deep cleans", "Restocking", "Photo reports", "Mold & mildew treatment"],
    responseTime: "Under 2 hours",
    insured: true,
    licensed: false,
    yearFounded: 2019,
    priceNote: "From $140 / turnover",
  },
  {
    slug: "fresh-stay-cleaning",
    name: "Fresh Stay Cleaning Co.",
    category: "cleaning",
    counties: ["Monroe"],
    serviceAreas: ["East Stroudsburg", "Swiftwater", "Bartonsville"],
    tier: "standard",
    phone: "5705550102",
    email: "book@freshstaycleaning.com",
    rating: 4.8,
    reviewCount: 27,
    verified: true,
    tagline: "Reliable turnovers with a same-day guarantee",
    description:
      "A dedicated crew focused on STR turnovers in the Stroudsburg area. Same-day service for same-day bookings, laundry pickup available, and consistent staffing so guests never see a different crew twice in a row.",
    services: ["Turnovers", "Laundry pickup", "Supply restock", "Guest-ready staging"],
    responseTime: "Same day",
    insured: true,
    licensed: false,
    yearFounded: 2021,
    priceNote: "From $125 / turnover",
  },
  {
    slug: "summit-housekeeping",
    name: "Summit Housekeeping",
    category: "cleaning",
    counties: ["Monroe", "Wayne"],
    serviceAreas: ["Mount Pocono", "Tobyhanna", "Gouldsboro"],
    tier: "standard",
    phone: "5705550103",
    email: "summit@summithousekeeping.com",
    rating: 4.7,
    reviewCount: 19,
    verified: true,
    tagline: "Weekend-peak turnovers without the stress",
    description:
      "We built our schedule around the Poconos weekend rush: Friday and Sunday crews that handle check-in and check-out waves, plus mid-week deep cleans for back-to-back bookings.",
    services: ["Turnovers", "Mid-week deep cleans", "Hot tub care", "Trash & recycling"],
    responseTime: "Under 4 hours",
    insured: true,
    licensed: false,
    yearFounded: 2020,
    priceNote: "From $130 / turnover",
  },
  {
    slug: "alpine-turnover-crew",
    name: "Alpine Turnover Crew",
    category: "cleaning",
    counties: ["Carbon", "Monroe"],
    serviceAreas: ["Lake Harmony", "Albrightsville", "Blakeslee", "Pocono Lake"],
    tier: "premium",
    phone: "5705550104",
    email: "crew@alpineturnover.com",
    website: "alpineturnover.com",
    rating: 4.9,
    reviewCount: 33,
    verified: true,
    tagline: "Lake-area specialists with 2-hour response",
    description:
      "Cleaning crews based in the Lake Harmony corridor covering the busiest lake-rental market in the Poconos. Two-hour emergency response, snow-ready access plans, and detailed turnover checklists that cut guest complaints in half.",
    services: ["Turnovers", "Emergency cleans", "Hot tub servicing", "Seasonal deep cleans"],
    responseTime: "2 hours",
    insured: true,
    licensed: false,
    yearFounded: 2018,
    priceNote: "From $150 / turnover",
  },
  {
    slug: "keystone-clean-team",
    name: "Keystone Clean Team",
    category: "cleaning",
    counties: ["Wayne"],
    serviceAreas: ["Honesdale", "Hawley", "Lake Wallenpaupack"],
    tier: "standard",
    phone: "5705550105",
    email: "info@keystonecleanteam.com",
    rating: 4.6,
    reviewCount: 14,
    verified: false,
    tagline: "Wayne County's STR turnover specialists",
    description:
      "Serving the Lake Wallenpaupack rental market with turnovers, restocking, and a 24-hour booking window. Trusted by local property managers for dependable weekend coverage.",
    services: ["Turnovers", "Restocking", "Pre-arrival checks"],
    responseTime: "Within 1 business day",
    insured: true,
    licensed: false,
    yearFounded: 2021,
    priceNote: "From $125 / turnover",
  },
  {
    slug: "white-pine-cleaning",
    name: "White Pine Cleaning",
    category: "cleaning",
    counties: ["Pike"],
    serviceAreas: ["Bushkill", "Dingmans Ferry", "Milford"],
    tier: "free",
    phone: "5705550106",
    email: "whitepinecleaning@gmail.com",
    rating: 4.5,
    reviewCount: 9,
    verified: false,
    tagline: "New crew building STR turnover clients",
    description:
      "Established residential cleaning company expanding into vacation rental turnovers in Pike County. Flexible scheduling and competitive introductory pricing for first-time STR clients.",
    services: ["Turnovers", "Residential cleans", "Move-out cleans"],
    responseTime: "Within 1 business day",
    insured: true,
    licensed: false,
    yearFounded: 2023,
    priceNote: "From $110 / turnover",
  },
  {
    slug: "mountain-man-repairs",
    name: "Mountain Man Repairs",
    category: "maintenance",
    counties: ["Monroe", "Carbon"],
    serviceAreas: ["Tannersville", "Stroudsburg", "Cresco", "Albrightsville"],
    tier: "featured",
    phone: "5705550111",
    email: "jim@mountainmanrepairs.com",
    website: "mountainmanrepairs.com",
    rating: 4.8,
    reviewCount: 52,
    verified: true,
    tagline: "The handyman hosts call first — 15+ years",
    description:
      "Full-service handyman for STR owners: drywall, painting, deck repair, furniture assembly, smart locks, and preventative winterization. We keep a punch-list app so owners know exactly what was fixed and when.",
    services: ["Drywall & paint", "Deck & fence repair", "Furniture assembly", "Smart lock installs", "Winterization"],
    responseTime: "Within 4 hours",
    insured: true,
    licensed: true,
    yearFounded: 2009,
    priceNote: "$85 / hr",
  },
  {
    slug: "pocono-handyman-pro",
    name: "Pocono Handyman Pro",
    category: "maintenance",
    counties: ["Monroe"],
    serviceAreas: ["Stroudsburg", "East Stroudsburg", "Saylorsburg"],
    tier: "standard",
    phone: "5705550112",
    email: "mike@poconohandymanpro.com",
    rating: 4.7,
    reviewCount: 31,
    verified: true,
    tagline: "Small repairs done right, same week",
    description:
      "Solo handyman with a strong local reputation for fast, fair-priced repairs on vacation rentals. Most small jobs are quoted same-day and completed within the week.",
    services: ["General repairs", "Caulking & sealing", "Door & lock repairs", "Light carpentry"],
    responseTime: "Same day",
    insured: true,
    licensed: false,
    yearFounded: 2016,
    priceNote: "$75 / hr",
  },
  {
    slug: "lake-effect-maintenance",
    name: "Lake Effect Maintenance",
    category: "maintenance",
    counties: ["Wayne", "Pike"],
    serviceAreas: ["Hawley", "Honesdale", "Lake Wallenpaupack", "Milford"],
    tier: "standard",
    phone: "5705550113",
    email: "service@lakeeffectmaint.com",
    rating: 4.6,
    reviewCount: 18,
    verified: false,
    tagline: "Two-county coverage for lakefront rentals",
    description:
      "Handyman and light maintenance services built around lakefront rentals: dock repairs, bulkhead checks, water-damage touch-ups, and seasonal opening/closing help.",
    services: ["Dock & bulkhead repair", "Water damage touch-up", "Seasonal opening/closing", "General repairs"],
    responseTime: "Within 24 hours",
    insured: true,
    licensed: false,
    yearFounded: 2019,
    priceNote: "$80 / hr",
  },
  {
    slug: "ridge-and-valley-repair",
    name: "Ridge & Valley Repair",
    category: "maintenance",
    counties: ["Carbon"],
    serviceAreas: ["Jim Thorpe", "Lehighton", "White Haven"],
    tier: "standard",
    phone: "5705550114",
    email: "ridgevalleyrepair@gmail.com",
    rating: 4.5,
    reviewCount: 11,
    verified: false,
    tagline: "Jim Thorpe area's go-to fix-it pro",
    description:
      "Reliable handyman serving the Jim Thorpe and Lehighton corridor with repairs, painting, and light carpentry for boutique rentals and historic homes.",
    services: ["Repairs", "Painting", "Light carpentry", "Gutter cleaning"],
    responseTime: "Within 1 business day",
    insured: true,
    licensed: false,
    yearFounded: 2020,
    priceNote: "$70 / hr",
  },
  {
    slug: "timberline-property-care",
    name: "Timberline Property Care",
    category: "maintenance",
    counties: ["Monroe"],
    serviceAreas: ["Canadensis", "Cresco", "Swiftwater"],
    tier: "free",
    phone: "5705550115",
    email: "timberlinepc@gmail.com",
    rating: 4.4,
    reviewCount: 6,
    verified: false,
    tagline: "Growing crew taking on rental maintenance",
    description:
      "Property care crew expanding into STR maintenance. Seasonal packages available that combine lawn, snow, and handyman work into one predictable monthly bill.",
    services: ["General repairs", "Seasonal maintenance packages", "Exterior upkeep"],
    responseTime: "Within 2 business days",
    insured: false,
    licensed: false,
    yearFounded: 2022,
    priceNote: "$65 / hr",
  },
  {
    slug: "pocono-climate-control",
    name: "Pocono Climate Control",
    category: "hvac",
    counties: ["Monroe", "Carbon"],
    serviceAreas: ["East Stroudsburg", "Tannersville", "Lake Harmony"],
    tier: "featured",
    phone: "5705550121",
    email: "service@poconoclimate.com",
    website: "poconoclimate.com",
    rating: 4.8,
    reviewCount: 44,
    verified: true,
    tagline: "Licensed HVAC with STR-speed emergency service",
    description:
      "Licensed and insured HVAC contractor that keeps rental properties guest-ready year-round. 24/7 emergency heat and AC service, annual maintenance plans for STR owners, and direct billing to property managers.",
    services: ["Furnace repair", "Heat pump service", "AC tune-ups", "Duct cleaning", "24/7 emergency calls"],
    responseTime: "24/7 emergency line",
    insured: true,
    licensed: true,
    yearFounded: 2011,
    priceNote: "$120 diagnostic",
  },
  {
    slug: "alpine-air-hvac",
    name: "Alpine Air HVAC",
    category: "hvac",
    counties: ["Monroe"],
    serviceAreas: ["Mount Pocono", "Tobyhanna", "Gouldsboro"],
    tier: "standard",
    phone: "5705550122",
    email: "office@alpineairhvac.com",
    rating: 4.6,
    reviewCount: 22,
    verified: true,
    tagline: "Heat pumps and mini-splits, done right",
    description:
      "Specialists in the heat pumps and mini-split systems common in newer Poconos rentals. Fast diagnostics, honest pricing, and after-hours availability for guest-facing breakdowns.",
    services: ["Mini-split install", "Heat pump repair", "Thermostat setup", "Emergency service"],
    responseTime: "Within 4 hours",
    insured: true,
    licensed: true,
    yearFounded: 2015,
    priceNote: "$95 diagnostic",
  },
  {
    slug: "high-country-hvac",
    name: "High Country Heating & Cooling",
    category: "hvac",
    counties: ["Pike", "Wayne"],
    serviceAreas: ["Milford", "Dingmans Ferry", "Hawley"],
    tier: "standard",
    phone: "5705550123",
    email: "highcountryhvac@gmail.com",
    rating: 4.7,
    reviewCount: 16,
    verified: false,
    tagline: "Pike & Wayne county heating coverage",
    description:
      "Family-owned HVAC serving the northern Poconos with furnace tune-ups, propane system checks, and rental-property maintenance agreements.",
    services: ["Furnace tune-ups", "Propane system checks", "AC repair", "Maintenance agreements"],
    responseTime: "Within 1 business day",
    insured: true,
    licensed: true,
    yearFounded: 2017,
    priceNote: "$110 diagnostic",
  },
  {
    slug: "clearwater-plumbing",
    name: "Clearwater Plumbing",
    category: "plumbing",
    counties: ["Monroe"],
    serviceAreas: ["Stroudsburg", "East Stroudsburg", "Bartonsville"],
    tier: "standard",
    phone: "5705550131",
    email: "clearwaterplumbing@gmail.com",
    rating: 4.7,
    reviewCount: 29,
    verified: true,
    tagline: "Licensed plumbers for rental-ready fixes",
    description:
      "Licensed plumbing company experienced with STR-specific issues: clogged drains from guest use, water heater replacements, and frozen-pipe emergencies in mountain homes.",
    services: ["Drain cleaning", "Water heaters", "Frozen pipe repair", "Leak detection"],
    responseTime: "Within 4 hours",
    insured: true,
    licensed: true,
    yearFounded: 2013,
    priceNote: "$150 service call",
  },
  {
    slug: "pocono-pipeworks",
    name: "Pocono Pipeworks",
    category: "plumbing",
    counties: ["Monroe", "Carbon"],
    serviceAreas: ["Tobyhanna", "Pocono Lake", "Albrightsville"],
    tier: "standard",
    phone: "5705550132",
    email: "poconopipeworks@gmail.com",
    rating: 4.5,
    reviewCount: 13,
    verified: false,
    tagline: "Rough-country plumbing for mountain homes",
    description:
      "Plumbers who understand well systems, septic-friendly fixes, and the quirks of mountain rentals. Preventive winterization plans available for remote properties.",
    services: ["Well systems", "Septic-friendly repair", "Winterization", "Fixture replacement"],
    responseTime: "Within 1 business day",
    insured: true,
    licensed: true,
    yearFounded: 2018,
    priceNote: "$140 service call",
  },
  {
    slug: "summit-plumbing-drain",
    name: "Summit Plumbing & Drain",
    category: "plumbing",
    counties: ["Carbon"],
    serviceAreas: ["Jim Thorpe", "Lehighton", "White Haven"],
    tier: "free",
    phone: "5705550133",
    email: "summitplumb@gmail.com",
    rating: 4.4,
    reviewCount: 8,
    verified: false,
    tagline: "Jim Thorpe plumbing, done local",
    description:
      "Local plumbing and drain service building a rental-property clientele in Carbon County. Fair rates and quick response on common guest-caused issues.",
    services: ["Drain clearing", "Toilet repair", "Fixture installs", "Leak repair"],
    responseTime: "Within 1 business day",
    insured: true,
    licensed: true,
    yearFounded: 2021,
    priceNote: "$125 service call",
  },
  {
    slug: "mountain-current-electric",
    name: "Mountain Current Electric",
    category: "electrical",
    counties: ["Monroe"],
    serviceAreas: ["Stroudsburg", "Tannersville", "Swiftwater"],
    tier: "premium",
    phone: "5705550141",
    email: "work@mountaincurrent.com",
    website: "mountaincurrent.com",
    rating: 4.9,
    reviewCount: 37,
    verified: true,
    tagline: "Licensed electricians for hot tubs & EV chargers",
    description:
      "Full-service electrical contractor popular with STR owners installing hot tubs, saunas, EV chargers, and smart-home systems. Code-compliant work with photos and permits handled for you.",
    services: ["Hot tub hookups", "EV chargers", "Panel upgrades", "Smart-home wiring", "Outdoor lighting"],
    responseTime: "Within 4 hours",
    insured: true,
    licensed: true,
    yearFounded: 2012,
    priceNote: "$135 service call",
  },
  {
    slug: "keystone-voltage",
    name: "Keystone Voltage",
    category: "electrical",
    counties: ["Wayne"],
    serviceAreas: ["Honesdale", "Hawley", "Lake Wallenpaupack"],
    tier: "standard",
    phone: "5705550142",
    email: "keystonevoltage@gmail.com",
    rating: 4.6,
    reviewCount: 15,
    verified: false,
    tagline: "Wayne County electrical, rental-savvy",
    description:
      "Licensed electricians serving lake-area rentals with inspections, repair, and upgrade work. Familiar with the permit requirements that catch new STR owners by surprise.",
    services: ["Electrical repair", "Inspections", "Hot tub wiring", "Fixture installs"],
    responseTime: "Within 1 business day",
    insured: true,
    licensed: true,
    yearFounded: 2016,
    priceNote: "$130 service call",
  },
  {
    slug: "blue-ridge-electric",
    name: "Blue Ridge Electric Co.",
    category: "electrical",
    counties: ["Pike"],
    serviceAreas: ["Milford", "Dingmans Ferry", "Bushkill"],
    tier: "standard",
    phone: "5705550143",
    email: "blueridgeelectric@outlook.com",
    rating: 4.5,
    reviewCount: 12,
    verified: false,
    tagline: "Pike County electrical you can book in advance",
    description:
      "Small licensed electrical shop with online booking — rare in the region. Great for scheduled upgrades and seasonal lighting installs between bookings.",
    services: ["Panel work", "Lighting installs", "Repairs", "Generator hookups"],
    responseTime: "Within 1 business day",
    insured: true,
    licensed: true,
    yearFounded: 2019,
    priceNote: "$125 service call",
  },
  {
    slug: "pocono-greenscapes",
    name: "Pocono Greenscapes",
    category: "landscaping",
    counties: ["Monroe"],
    serviceAreas: ["Tannersville", "Bartonsville", "Stroudsburg"],
    tier: "standard",
    phone: "5705550151",
    email: "poconogreenscapes@gmail.com",
    rating: 4.7,
    reviewCount: 21,
    verified: true,
    tagline: "Curb appeal that shows up in your photos",
    description:
      "Landscaping designed to keep vacation rentals photo-ready: mowing, mulching, stone work, and seasonal color. Monthly plans that sync with your booking calendar.",
    services: ["Mowing", "Mulching & beds", "Stone & hardscape", "Seasonal color"],
    responseTime: "Within 1 business day",
    insured: true,
    licensed: false,
    yearFounded: 2017,
    priceNote: "From $220 / month",
  },
  {
    slug: "evergreen-lawn-landscape",
    name: "Evergreen Lawn & Landscape",
    category: "landscaping",
    counties: ["Monroe"],
    serviceAreas: ["Cresco", "Canadensis", "Effort"],
    tier: "standard",
    phone: "5705550152",
    email: "evergreenll@yahoo.com",
    rating: 4.5,
    reviewCount: 10,
    verified: false,
    tagline: "Keep the yard as clean as the interior",
    description:
      "Full lawn and landscape service for the quieter corners of Monroe County. Reliable weekly schedules and clean-up after every storm.",
    services: ["Lawn care", "Brush clearing", "Storm cleanup", "Spring/fall cleanups"],
    responseTime: "Within 2 business days",
    insured: true,
    licensed: false,
    yearFounded: 2020,
    priceNote: "From $180 / month",
  },
  {
    slug: "woodland-outdoor-services",
    name: "Woodland Outdoor Services",
    category: "landscaping",
    counties: ["Carbon"],
    serviceAreas: ["Lake Harmony", "Albrightsville", "Blakeslee"],
    tier: "free",
    phone: "5705550153",
    email: "woodlandoutdoors@gmail.com",
    rating: 4.4,
    reviewCount: 7,
    verified: false,
    tagline: "Outdoor maintenance for lake rentals",
    description:
      "Outdoor services for lake-area rentals: lawn care, brush control, fire-pit maintenance, and lakeside cleanup between seasons.",
    services: ["Lawn care", "Fire-pit upkeep", "Brush control", "Lakeside cleanup"],
    responseTime: "Within 2 business days",
    insured: false,
    licensed: false,
    yearFounded: 2021,
    priceNote: "From $160 / month",
  },
  {
    slug: "keystone-snow-pros",
    name: "Keystone Snow Pros",
    category: "snow-removal",
    counties: ["Monroe", "Carbon"],
    serviceAreas: ["Stroudsburg", "Tannersville", "Lake Harmony", "Blakeslee"],
    tier: "featured",
    phone: "5705550161",
    email: "dispatch@keystonesnowpros.com",
    website: "keystonesnowpros.com",
    rating: 4.8,
    reviewCount: 26,
    verified: true,
    tagline: "STR-first plowing with access guarantee",
    description:
      "Snow service built for rental hosts: guaranteed driveway and walkway access before check-in, 24/7 storm dispatch, and photo proof of service after every plow. Seasonal contracts hold your spot for winter bookings.",
    services: ["Driveway plowing", "Walkway shoveling", "Ice treatment", "24/7 storm dispatch", "Seasonal contracts"],
    responseTime: "24/7 during storms",
    insured: true,
    licensed: false,
    yearFounded: 2018,
    priceNote: "From $120 / storm",
  },
  {
    slug: "north-slope-snow-ice",
    name: "North Slope Snow & Ice",
    category: "snow-removal",
    counties: ["Carbon"],
    serviceAreas: ["White Haven", "Jim Thorpe", "Albrightsville"],
    tier: "standard",
    phone: "5705550162",
    email: "northslopesnow@gmail.com",
    rating: 4.6,
    reviewCount: 14,
    verified: false,
    tagline: "Steep-driveway specialists for mountain homes",
    description:
      "We handle the steep, tricky driveways that other plows won't touch. Snow, ice, and de-icing packages for rentals that host winter guests.",
    services: ["Steep-driveway plowing", "De-icing", "Roof raking", "Seasonal contracts"],
    responseTime: "24/7 during storms",
    insured: true,
    licensed: false,
    yearFounded: 2019,
    priceNote: "From $140 / storm",
  },
  {
    slug: "arctic-poconos-plow",
    name: "Arctic Poconos Plow",
    category: "snow-removal",
    counties: ["Wayne", "Pike"],
    serviceAreas: ["Hawley", "Honesdale", "Milford"],
    tier: "free",
    phone: "5705550163",
    email: "arcticpoconosplow@gmail.com",
    rating: 4.5,
    reviewCount: 9,
    verified: false,
    tagline: "Northern Poconos plow service, per-storm or seasonal",
    description:
      "Flexible plowing service for the northern counties. Book per-storm or commit to a seasonal contract and never worry about check-in-day snow again.",
    services: ["Plowing", "Shoveling", "Ice treatment"],
    responseTime: "Within 12 hours of storm end",
    insured: true,
    licensed: false,
    yearFounded: 2020,
    priceNote: "From $100 / storm",
  },
  {
    slug: "pocono-linen-supply",
    name: "Pocono Linen Supply",
    category: "linens",
    counties: ["Monroe", "Carbon"],
    serviceAreas: ["East Stroudsburg", "Tannersville", "Lake Harmony"],
    tier: "premium",
    phone: "5705550171",
    email: "sales@poconolinens.com",
    website: "poconolinens.com",
    rating: 4.9,
    reviewCount: 30,
    verified: true,
    tagline: "Hotel-grade linens delivered on your turnover day",
    description:
      "Commercial-grade sheet sets, towel bundles, and amenities delivered and picked up on your exact turnover schedule. Barcode-tracked bundles so nothing goes missing between houses.",
    services: ["Sheet sets", "Towel bundles", "Amenity refills", "Scheduled pickup", "Barcode tracking"],
    responseTime: "Same day",
    insured: false,
    licensed: false,
    yearFounded: 2019,
    priceNote: "From $2.25 / bed set",
  },
  {
    slug: "alpine-threads",
    name: "Alpine Threads Linen Co.",
    category: "linens",
    counties: ["Monroe"],
    serviceAreas: ["Mount Pocono", "Tobyhanna", "Gouldsboro"],
    tier: "standard",
    phone: "5705550172",
    email: "alpthreads@gmail.com",
    rating: 4.7,
    reviewCount: 17,
    verified: false,
    tagline: "Soft, consistent linens that earn 5-star reviews",
    description:
      "Linen rental for STR owners who want that hotel feel without the laundry headache. Consistent product so every guest gets the same great sheets.",
    services: ["Linen rental", "Towel service", "Bulk laundering"],
    responseTime: "Within 1 business day",
    insured: false,
    licensed: false,
    yearFounded: 2020,
    priceNote: "From $2.00 / bed set",
  },
  {
    slug: "lakeside-laundry-co",
    name: "Lakeside Laundry Co.",
    category: "linens",
    counties: ["Carbon", "Wayne"],
    serviceAreas: ["Lake Harmony", "Albrightsville", "Hawley", "Lake Wallenpaupack"],
    tier: "standard",
    phone: "5705550173",
    email: "lakesidelaundry@gmail.com",
    rating: 4.6,
    reviewCount: 13,
    verified: false,
    tagline: "Lake-area linen service with same-week delivery",
    description:
      "Lake-district linen service covering the two biggest lake markets. Wash-and-fold for your own linens or full rental packages for new hosts.",
    services: ["Wash & fold", "Linen packages", "Towel bundles"],
    responseTime: "Within 2 business days",
    insured: false,
    licensed: false,
    yearFounded: 2021,
    priceNote: "From $1.80 / bed set",
  },
  {
    slug: "pocono-property-photography",
    name: "Pocono Property Photography",
    category: "photography",
    counties: ["Monroe", "Carbon"],
    serviceAreas: ["Stroudsburg", "Tannersville", "Lake Harmony"],
    tier: "standard",
    phone: "5705550181",
    email: "book@poconophoto.com",
    website: "poconopropertyphoto.com",
    rating: 4.8,
    reviewCount: 24,
    verified: true,
    tagline: "Photos that lift your ranking and nightly rate",
    description:
      "Real-estate and STR photographers who shoot twilight exteriors, HDR interiors, and 3D virtual tours. Hosts see higher click-through and bookings within weeks of a reshoot.",
    services: ["HDR interiors", "Twilight exteriors", "3D virtual tours", "Drone video", "Floor plans"],
    responseTime: "Books within 1 week",
    insured: false,
    licensed: false,
    yearFounded: 2016,
    priceNote: "From $275 / shoot",
  },
  {
    slug: "lake-light-media",
    name: "Lake Light Media",
    category: "photography",
    counties: ["Wayne", "Pike"],
    serviceAreas: ["Lake Wallenpaupack", "Hawley", "Milford"],
    tier: "standard",
    phone: "5705550182",
    email: "hello@lakelightmedia.com",
    rating: 4.7,
    reviewCount: 15,
    verified: false,
    tagline: "Lakefront property specialists",
    description:
      "Photography and video focused on lakefront and lake-view rentals. Drone footage of shoreline, docks, and sunset views that sell the lifestyle.",
    services: ["Interior photography", "Drone footage", "Property video", "Twilight shoots"],
    responseTime: "Books within 2 weeks",
    insured: false,
    licensed: false,
    yearFounded: 2019,
    priceNote: "From $300 / shoot",
  },
  {
    slug: "summit-staging-studio",
    name: "Summit Staging Studio",
    category: "photography",
    counties: ["Monroe"],
    serviceAreas: ["Tannersville", "Mount Pocono", "Cresco"],
    tier: "free",
    phone: "5705550183",
    email: "summitstaging@gmail.com",
    rating: 4.5,
    reviewCount: 7,
    verified: false,
    tagline: "Styling + photography for boutique rentals",
    description:
      "Small staging and photography studio helping boutique rentals and cabins stand out. Styling consultations, prop styling, and flat-lay product shots for amenities.",
    services: ["Interior styling", "Prop styling", "Product photography"],
    responseTime: "Books within 2 weeks",
    insured: false,
    licensed: false,
    yearFounded: 2022,
    priceNote: "From $200 / session",
  },
];

export const FEATURED = PROVIDERS.filter((p) => p.tier === "featured");

export function getProvidersByCategory(slug: string): Provider[] {
  return PROVIDERS.filter((p) => p.category === slug);
}

export function getProviderBySlug(slug: string): Provider | undefined {
  return PROVIDERS.find((p) => p.slug === slug);
}

export const COUNTIES = ["Monroe", "Pike", "Carbon", "Wayne"] as const;
