import type { Provider } from "./types";

export const INITIAL_POCONOS_PROVIDERS: Provider[] = [
  {
    slug: "mountain-cleaning",
    name: "Mountain Cleaning Services LLC",
    category: "cleaning",
    counties: ["Monroe", "Carbon", "Pike"],
    serviceAreas: ["Blakeslee", "Lake Harmony", "Albrightsville", "Tobyhanna", "Mount Pocono", "Tannersville"],
    tier: "featured",
    phone: "(570) 781-5070",
    website: "mountaincleaningservicesllc.com",
    rating: 4.9,
    reviewCount: 38,
    verified: true,
    tagline: "STR turnovers + hot tub balancing + guest-ready guarantee.",
    description:
      "Mountain Cleaning Services handles complete turnover cleaning for short-term rentals across the Poconos. Services include deep cleaning, linen handling, hot tub maintenance and balancing, guest-ready staging, and 24/7 emergency support for check-in day issues.",
    services: ["STR turnovers", "Hot tub service", "Linen handling", "Guest-ready guarantee", "Emergency support"],
    responseTime: "Under 2 hours",
    insured: true,
    licensed: false,
    yearFounded: 2012,
    pricingNotes: "STR turnovers + hot tub balancing + guest-ready guarantee.",
    featuredResorts: ["Lake Harmony", "Camelback / Tannersville"],
  },
  {
    slug: "hot-tub-hygiene",
    name: "Hot Tub Hygiene",
    category: "hottub",
    counties: ["Monroe", "Carbon"],
    serviceAreas: ["East Stroudsburg", "Stroudsburg", "Lake Harmony", "Tobyhanna"],
    tier: "premium",
    phone: "Request via site",
    email: "Contact@Hottubhygiene.com",
    website: "hottubhygiene.com",
    rating: 4.8,
    reviewCount: 22,
    verified: true,
    tagline: "Hot tub chemical balancing, drain & refill, and maintenance for vacation rentals.",
    description:
      "Hot Tub Hygiene specializes exclusively in hot tub care for Pocono vacation rentals. Chemical balancing, cleaning, cover replacement, drain and refill, and winterization services. Online booking, text support, and guest-safety certified technicians.",
    services: ["Chemical balancing", "Drain & refill", "Cover cleaning/replacement", "Winterization", "24/7 guest support"],
    responseTime: "Same day",
    insured: true,
    licensed: true,
    yearFounded: 2018,
    pricingNotes: "$80-$150 per visit; chemical balancing, drain/refill.",
    featuredResorts: ["Lake Harmony"],
  },
  {
    slug: "blue-titan",
    name: "Blue Titan Plumbing & Heating",
    category: "hvac",
    counties: ["Monroe", "Carbon", "Pike", "Wayne"],
    serviceAreas: ["Monroe", "Carbon", "Pike", "Wayne"],
    tier: "premium",
    phone: "(570) 545-6199",
    website: "bluetitanhvac.com",
    rating: 4.7,
    reviewCount: 45,
    verified: true,
    tagline: "HVAC, plumbing, and seasonal winterization for vacation homes.",
    description:
      "Blue Titan provides full-service plumbing, heating, and air conditioning for Pocono vacation rentals. Seasonal winterization packages, 24/7 emergency service, smart thermostat integration, and direct billing to property managers.",
    services: ["HVAC repair/install", "Plumbing", "Winterization", "Smart thermostat setup", "24/7 emergency"],
    responseTime: "24/7 emergency",
    insured: true,
    licensed: true,
    yearFounded: 2010,
    pricingNotes: "Seasonal winterization packages, 24/7 vacation-home focus.",
    featuredResorts: ["Camelback / Tannersville", "Blue Mountain", "Shawnee"],
  },
  {
    slug: "the-tidy-bear",
    name: "The Tidy Bear",
    category: "trash",
    counties: ["Monroe", "Carbon"],
    serviceAreas: ["Poconos-wide"],
    tier: "standard",
    phone: "Request via site",
    website: "thetidybear.com",
    rating: 4.6,
    reviewCount: 19,
    verified: true,
    tagline: "Weekly trash valet, recycling pickup, and can cleaning for STR hosts.",
    description:
      "The Tidy Bear handles trash and recycling removal for vacation rental hosts. Weekly pickup and return of cans, recycling sorting, and seasonal deep-cleaning of outdoor receptacles. Flat monthly rate so hosts never worry about garbage day.",
    services: ["Weekly trash valet", "Recycling pickup", "Can cleaning", "Seasonal deep clean", "Text reminders"],
    responseTime: "Weekly scheduled",
    insured: true,
    licensed: false,
    yearFounded: 2021,
    pricingNotes: "From $49/month for weekly can take-out & return.",
    featuredResorts: ["Poconos-wide"],
  },
];
